### ISSUE TITLE
IMPORTANT: Password Reset Implementation/Email Notification/Scheduling Bug for Milestone

### ISSUE THREAD

**Issue by gghafir** [mrjones2014/FixedIt#15]
These issues already exist, just making sure the issue is on the top of the priority list.

**Comment by mrjones2014** [comment]
Password reset system implemented - see issue #14

**Comment by mrjones2014** [comment]
- [x] Password reset system
- [ ] Account creation confirmation email
- [ ] Schedule "ghosting" bug

**Comment by mrjones2014** [comment]
Pretty sure the schedule ghosting bug was fixed by something we updated, I haven't experienced it in quite a while. I think it was caused by generally having numerous database and user session bugs; I think fixing those fixed the ghosting bug. Closing this issue.
